; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
platform = atmelavr
board = uno
framework = arduino
monitor_speed = 115200
build_flags =
    -D ETL_NO_STL
    -Iinclude
lib_deps =
    etlcpp/Embedded Template Library@20.39.4
    adafruit/Adafruit BME280 Library@^2.2.4
    adafruit/Adafruit Unified Sensor@^1.1.14
    adafruit/Adafruit BusIO@^1.15.0

[env:uno_i2c]
build_src_filter = +<*> -<main_spi.cpp>

[env:uno_spi]
build_src_filter = +<*> -<main_i2c.cpp>